# Generated by Django 5.2.6 on 2025-09-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_userprofile_options_userprofile_age_and_more'),
    ]

    operations = [
    ]
